<?php
const IS_MASSAGE = 'massage';
const IS_NAIL = 'nail';
const IS_EYE = 'eye';

$serviceData = array(
    [
        "title" => "Balinese Massage",
        "url" => "https://xinspabeauty.com/",
        "icon" => "icon-massage-1",
        "is-icon-image" => false,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-balinesemassage.jpg",
        "description" => "The Balinese massage offers an exceptional blend of techniques to achieve deep relaxation, release muscle tension and promote overall health.",
    ],
    [
        "title" => "Nail Art",
        "url" => "https://xinspabeauty.com/",
        "icon" => "icon-hand-cream",
        "is-icon-image" => false,
        'type' => IS_NAIL,
        "image" => "assets/images/services/services-1-1.jpg",
        "description" => "With nail decoration becoming a fun and innovative outlet for self-expression, the growing trend of nail art has captured the interest of many.",
    ],
    [
        "title" => "Eyelash",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/007-eyelash.svg",
        "is-icon-image" => true,
        'type' => IS_EYE,
        "image" => "assets/images/services/services-eyelash.jpg",
        "description" => "Eyelash extensions have become a popular beauty trend, offering individuals the opportunity to enhance the length, fullness, and curl of their natural lashes.",
    ],
    [
        "title" => "Reflexology",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/006-foot-massage.svg",
        "is-icon-image" => true,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-refleksologi.jpg",
        "description" => "Reflex zone massage is the beautiful art of touch, connecting points on the feet and hands with the organs of the body to stimulate natural recovery.",
    ],
    [
        "title" => "Head and Shoulder Massage",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/001-relax.svg",
        "is-icon-image" => true,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-h&s.jpg",
        "description" => "Head and shoulder massage is a popular technique that is focused on the release of tension and the promotion of relaxation in the upper body.",
    ],
    [
        "title" => "Thai Massage",
        "url" => "https://xinspabeauty.com/",
        "icon" => "icon-spa-1",
        "is-icon-image" => false,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-thaimassage.jpg",
        "description" => "Thai massage is a traditional form of healing that has been practised in Thailand for hundreds of years. It creates a therapeutic experience.",
    ],
    [
        "title" => "Shiatsu Massage",
        "url" => "https://xinspabeauty.com/",
        "icon" => "icon-aroma",
        "is-icon-image" => false,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-shiatsu.jpg",
        "description" => "Shiatsu massage is a Japanese form of bodywork in which pressure is applied to specific points on the body in order to promote relaxation.",
    ],
    [
        "title" => "Sunburn Massage",
        "url" => "https://xinspabeauty.com/",
        "icon" => "icon-hand-cream",
        "is-icon-image" => false,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-sunburn.jpg",
        "description" => "Sunburn massage is a specialised form of massage therapy that is designed to provide relief and comfort to people who have suffered from sunburn.",
    ],
    [
        "title" => "Hot Stone",
        "url" => "https://xinspabeauty.com/",
        "icon" => "icon-spa",
        "is-icon-image" => false,
        'type' => IS_MASSAGE,
        "image" => "assets/images/services/services-hotstone.jpg",
        "description" => "Hot Stone Massage is a popular and luxurious type of massage treatment that uses soft, heated stones applied to certain parts of the body to promote relaxation and release tension.",
    ],
    [
        "title" => "Nails Manicure",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/003-manicure.svg",
        "is-icon-image" => true,
        'type' => IS_NAIL,
        "image" => "assets/images/services/services-manicure.jpg",
        "description" => "Manicuring is beauty treatment designed to improve nail and hand appearance and health. Typically, nails are shaped, buffed and painted.",
    ],
    [
        "title" => "Nails Pedicure",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/009-legs.svg",
        "is-icon-image" => true,
        'type' => IS_NAIL,
        "image" => "assets/images/services/services-pedicure.jpg",
        "description" => "Nails Pedicure is a popular beauty treatment that focuses on the care and beautification of the toenails and feet.",
    ],
    [
        "title" => "Nails Nail Gel",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/005-nail-1.svg",
        "is-icon-image" => true,
        'type' => IS_NAIL,
        "image" => "assets/images/services/services-nailgel.jpg",
        "description" => "Nails Nail Gel is a versatile option for those looking to add a touch of glamour to their nails, offering a wide range of colours, finishes and designs.",
    ],
    [
        "title" => "Nails Kid",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/006-nail-2.svg",
        "is-icon-image" => true,
        'type' => IS_NAIL,
        "image" => "assets/images/services/services-nailkid.jpg",
        "description" => "Nails Kid is a term used to describe nail care services designed specifically for kids. It's no surprise that children are interested in having their nails done.",
    ],
    [
        "title" => "Nails Man",
        "url" => "https://xinspabeauty.com/",
        "icon" => "assets/images/icon/services/002-nail.svg",
        "is-icon-image" => true,
        'type' => IS_NAIL,
        "image" => "assets/images/services/services-nailman.jpg",
        "description" => "Nails Man is a growing trend in men's grooming, with men increasingly incorporating nails into their grooming regimes.",
    ],
);